apiVersion: apps/v1
kind: Deployment
metadata:
  name: icdemo
  namespace: icdemo
  labels:
    robinapp: icdemo
    app: icdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: icdemo
  template:
    metadata:
      labels:
        app: icdemo
        robinapp: icdemo
    spec:
      containers:
      - name: icdemo
        image: slievens/ibmclouddemo
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: demo-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080