apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: icdemo
  labels:
    robinapp: icdemo
spec:
  storageClassName: robin
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
