apiVersion: v1
kind: Service
metadata:
  namespace: icdemo
  labels:
    robinapp: icdemo
    app: mongo
  name: mongo-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  type: LoadBalancer

